default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "share_lock_development" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { "5432" } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "share_lock_development" } %>_test
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { "5432" } %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB") { "share_lock" } %>_production
    username: <%= ENV.fetch("POSTGRES_USER") { "share_lock" } %>
    password: <%= ENV["SHARE_LOCK_DATABASE_PASSWORD"] %>
    host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
    port: <%= ENV.fetch("POSTGRES_PORT") { "5432" } %>
  cache:
    <<: *primary_production
    database: share_lock_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: share_lock_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: share_lock_production_cable
    migrations_paths: db/cable_migrate
